"""
Checking a project against what a library says it needs.

These checks are advisory. Nothing here blocks an install, because a project can
be laid out in ways this cannot read, and being wrong must never stop someone
using the library. The value is catching the common mistakes before they turn
into a linker error that says nothing useful.

Two sources of truth are read, both generated by CubeMX:

    stm32xxxx_hal_conf.h   which HAL modules are compiled in
    *.ioc                  which peripherals and middleware are configured
"""

import re
from pathlib import Path

# "#define HAL_SPI_MODULE_ENABLED", but not the commented out form CubeMX
# leaves behind for modules that are switched off.
HAL_MODULE = re.compile(r"^[^\S\n]*#define[^\S\n]+HAL_([A-Z0-9_]+)_MODULE_ENABLED", re.MULTILINE)

# CubeMX records configured peripherals as Mcu.IP0=SPI1, Mcu.IP1=FREERTOS, ...
IOC_IP = re.compile(r"^Mcu\.IP\d+=(.+)$", re.MULTILINE)

SEARCH_DEPTH = 4

OK = "ok"
WARN = "warn"
INFO = "info"


class Finding:
    """One observation about the project, with how seriously to take it."""

    def __init__(self, level, message, hint=""):
        self.level = level
        self.message = message
        self.hint = hint

    def __repr__(self):
        return f"Finding({self.level}, {self.message!r})"


def _find(project_root, pattern):
    """Find files matching a glob, without walking the whole disk."""
    root = Path(project_root)
    found = []

    for depth in range(SEARCH_DEPTH):
        found.extend(root.glob("/".join(["*"] * depth + [pattern])))

    return [p for p in found if p.is_file()]


def find_hal_conf(project_root):
    """The CubeMX generated HAL configuration header, when there is one."""
    matches = _find(project_root, "stm32*_hal_conf.h")

    return matches[0] if matches else None


def find_ioc(project_root):
    """The CubeMX project file, when there is one."""
    matches = _find(project_root, "*.ioc")

    return matches[0] if matches else None


def enabled_hal_modules(hal_conf):
    """Names of HAL modules switched on, lower case, for example {'spi', 'gpio'}."""
    if hal_conf is None:
        return set()

    try:
        text = Path(hal_conf).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()

    return {name.lower() for name in HAL_MODULE.findall(text)}


def configured_peripherals(ioc):
    """Peripherals and middleware CubeMX has configured, lower case."""
    if ioc is None:
        return set()

    try:
        text = Path(ioc).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()

    return {value.strip().lower() for value in IOC_IP.findall(text)}


def detect_rtos(project_root, peripherals=None):
    """
    Which operating system the project uses, if any.

    Looks at what CubeMX configured first, then falls back to looking for the
    headers, since a project can carry an RTOS that CubeMX did not add.
    """
    peripherals = peripherals or set()

    if any("freertos" in p for p in peripherals):
        return "freertos"

    if any("threadx" in p for p in peripherals):
        return "threadx"

    if _find(project_root, "cmsis_os2.h"):
        return "cmsis-os2"

    if _find(project_root, "FreeRTOS.h"):
        return "freertos"

    if _find(project_root, "cmsis_os.h"):
        return "cmsis-os2"

    return None


def _peripheral_present(wanted, configured):
    """
    Whether a wanted peripheral looks configured.

    CubeMX names instances, so a library asking for "spi" is satisfied by SPI1,
    SPI2 and so on. Matching is by prefix for that reason.
    """
    return any(name.startswith(wanted) for name in configured)


def check(manifest, project_root):
    """
    Compare a library's requirements against the project.

    Returns a list of Finding. An empty list means either everything matched or
    there was nothing to match against.
    """
    project_root = Path(project_root)
    requires = manifest.requires
    findings = []

    if requires.is_empty():
        return findings

    hal_conf = find_hal_conf(project_root)
    ioc = find_ioc(project_root)
    modules = enabled_hal_modules(hal_conf)
    peripherals = configured_peripherals(ioc)

    if hal_conf is None and ioc is None:
        if not requires.is_empty():
            findings.append(
                Finding(
                    INFO,
                    "Could not find a CubeMX project here, so nothing was verified.",
                    "Run this from the root of your STM32 project to have it checked.",
                )
            )
        return findings

    # HAL modules, read from stm32xxxx_hal_conf.h
    for module in requires.hal_modules:
        if hal_conf is None:
            continue

        if module in modules:
            findings.append(Finding(OK, f"HAL {module.upper()} module is enabled"))
        else:
            findings.append(
                Finding(
                    WARN,
                    f"HAL {module.upper()} module is not enabled",
                    f"Uncomment HAL_{module.upper()}_MODULE_ENABLED in {hal_conf.name}, "
                    f"or enable it in CubeMX and regenerate.",
                )
            )

    # Peripherals, read from the .ioc
    for peripheral in requires.peripherals:
        if ioc is None:
            continue

        if _peripheral_present(peripheral.type, peripherals):
            findings.append(Finding(OK, f"{peripheral.type.upper()} is configured"))
        else:
            findings.append(
                Finding(
                    WARN,
                    f"No {peripheral.type.upper()} found in your CubeMX configuration",
                    f"This library needs {peripheral.describe()}.",
                )
            )

    # Operating system
    if requires.needs_rtos:
        found = detect_rtos(project_root, peripherals)

        if found is None:
            findings.append(
                Finding(
                    WARN,
                    "This library needs an RTOS and none was found",
                    f"It expects {requires.rtos}. Enable it in CubeMX under Middleware.",
                )
            )
        elif requires.rtos in ("any", found):
            findings.append(Finding(OK, f"{found} is present"))
        else:
            findings.append(
                Finding(
                    WARN,
                    f"This library expects {requires.rtos}, but the project uses {found}",
                    "It may still work, but it has not been tested that way.",
                )
            )

    return findings
