"""
CMake projects, which covers VS Code and the CMake output of recent CubeMX.

The library gets its own CMakeLists.txt holding its file list, and the project's
CMakeLists.txt gets two lines that never change no matter how many files the
library grows to.

That library target is an INTERFACE library, not a STATIC one, and the
difference is not cosmetic. A driver's .c file includes main.h, which reaches
the HAL headers, which need the device macro and the driver include paths. CubeMX
sets those on the executable target, so a STATIC library would not see them and
would fail to compile. An INTERFACE library hands its sources to whoever links
it, so they are compiled as part of the application and inherit everything it has.
"""

import re
from pathlib import Path

from .base import (
    ALREADY,
    CHANGED,
    MANUAL,
    MARK_CLOSE,
    MARK_OPEN,
    Outcome,
    backup,
    line_ending,
    read,
    relative,
    write,
)

NAME = "CMake"

LIBRARY_FILE = "CMakeLists.txt"

# add_executable(my_app ...) or add_library(my_lib ...)
TARGET = re.compile(r"^\s*add_(?:executable|library)\s*\(\s*([^\s)]+)", re.MULTILINE)

# CubeMX generated CMake projects define the target through the project() name.
PROJECT = re.compile(r"^\s*project\s*\(\s*([^\s)]+)", re.MULTILINE)

# target_link_libraries(<target> <first thing after it>
LINK_CALL = re.compile(r"target_link_libraries\s*\(\s*([^\s)]+)\s+([^\s)]+)")

# A block this tool wrote previously, so it can be ignored when reading the file.
OWN_BLOCK = re.compile(r"# >>> stm32-installer:.*?# <<< stm32-installer:[^\n]*\n?", re.DOTALL)

KEYWORDS = ("PRIVATE", "PUBLIC", "INTERFACE")


def _target_name(library):
    """
    What to call the generated library target.

    Suffixed on purpose. A project is very often named after the library being
    tried out in it, and CMake refuses to create two targets with one name.
    Testing fsm in a CubeMX project called fsm is exactly how this shows up.
    """
    return f"{library.name}_lib"


def _uses_plain_signature(text):
    """
    Whether this project already links libraries without a PRIVATE keyword.

    CMake refuses to mix the plain and keyword forms on one target, and the
    CubeMX template uses the plain one, so matching what is already there is
    not a matter of style. Getting it wrong fails every CubeMX CMake project.
    """
    # Blocks this tool wrote are skipped, or a second install would read its own
    # keyword form back and decide the project uses keywords.
    for match in LINK_CALL.finditer(OWN_BLOCK.sub("", text)):
        if match.group(2).upper() not in KEYWORDS:
            return True

    return False


def detect(project_root):
    """The project's CMakeLists.txt, when this looks like a CMake project."""
    candidate = Path(project_root) / "CMakeLists.txt"

    return candidate if candidate.is_file() else None


def _find_target(text):
    """
    The CMake target to attach the library to.

    Prefers an explicit add_executable, since that is the firmware itself. Falls
    back to ${CMAKE_PROJECT_NAME}, which is what the CubeMX template uses.
    """
    match = TARGET.search(text)

    if match:
        return match.group(1)

    if PROJECT.search(text):
        return "${CMAKE_PROJECT_NAME}"

    return None


def _library_cmakelists(library):
    """The CMakeLists.txt written into the library's own folder."""
    target = _target_name(library)
    listed = "\n".join(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/{name}" for name in library.build_sources)
    includes = " ".join(
        "${CMAKE_CURRENT_SOURCE_DIR}" if d == "." else f"${{CMAKE_CURRENT_SOURCE_DIR}}/{d}"
        for d in library.include_dirs
    )

    label = f"{library.name} {library.version}".strip()

    return f"""# Generated by stm32-installer for {label}.
#
# INTERFACE, not STATIC, on purpose. These sources are compiled as part of your
# own target, so they inherit its defines and include paths. That is what lets
# the library's .c files find main.h and the HAL headers. A STATIC library would
# not see them and would fail to compile.
#
# The target is called {target} rather than {library.name}, because a project is often
# named after the library being tried out in it, and CMake allows only one
# target of a given name.
#
# This file is written again on every install and update, so a change made
# here does not last. The files come from the library's library.yml.

add_library({target} INTERFACE)

target_sources({target} INTERFACE
{listed}
)

target_include_directories({target} INTERFACE {includes})
"""


def _block(library, folder, plain):
    """The two lines this tool owns inside the user's CMakeLists.txt."""
    target = _target_name(library)
    link = f"target_link_libraries(@TARGET@ {target})" if plain else (
        f"target_link_libraries(@TARGET@ PRIVATE {target})"
    )

    return (
        f"{MARK_OPEN.format(name=library.name)}\n"
        f"# Added by stm32-installer. Delete this block to drop the library from\n"
        f"# the build. Its file list lives in {folder}/{LIBRARY_FILE}.\n"
        f"add_subdirectory({folder})\n"
        f"{link}\n"
        f"{MARK_CLOSE.format(name=library.name)}"
    )


def integrate(cmakelists, library, destination, project_root):
    """Give the library its own CMakeLists.txt, then point the project at it."""
    path = Path(cmakelists)
    folder = relative(destination, project_root)

    try:
        text = read(path)
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not read {path.name}: {error}",
                       _manual_steps(folder, library))

    target = _find_target(text)

    if target is None:
        return Outcome(
            NAME,
            MANUAL,
            f"Could not find an add_executable or project call in {path.name}.",
            _manual_steps(folder, library),
        )

    # Written every time, so adding a source file to a library reaches everyone
    # who updates, without them editing anything.
    try:
        write(Path(destination) / LIBRARY_FILE, _library_cmakelists(library))
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not write {folder}/{LIBRARY_FILE}: {error}",
                       _manual_steps(folder, library))

    newline = line_ending(text)

    # Built with the line ending the file already uses, and before the block is
    # compared with the one already in the file. Comparing a block built with
    # line feeds against a stored block written with CRLF never matches, and the
    # integration would rewrite the file and take a backup on every single run.
    block = _block(library, folder, _uses_plain_signature(text)).replace("@TARGET@", target)
    block = block.replace("\n", newline)

    open_mark = MARK_OPEN.format(name=library.name)
    close_mark = MARK_CLOSE.format(name=library.name)

    if open_mark in text:
        start = text.index(open_mark)

        if close_mark not in text:
            return Outcome(
                NAME,
                MANUAL,
                f"{path.name} has a half written stm32-installer block. Fix it by hand first.",
                _manual_steps(folder, library),
            )

        end = text.index(close_mark) + len(close_mark)

        if text[start:end] == block:
            return Outcome(NAME, ALREADY, f"{path.name} already has {library.name}.")

        saved = backup(path)
        updated = text[:start] + block + text[end:]
    else:
        saved = backup(path)
        updated = text.rstrip("\r\n") + newline + newline + block + newline

    try:
        write(path, updated)
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not write {path.name}: {error}",
                       _manual_steps(folder, library), saved)

    return Outcome(
        NAME,
        CHANGED,
        f"Added {library.name} to {path.name}, linked to {target}.",
        backup=saved,
    )


def _manual_steps(folder, library):
    """What to paste in, when this could not do it safely."""
    return [
        "Add this to your CMakeLists.txt, using your own target name:",
        f"add_subdirectory({folder})",
        f"target_link_libraries(your_target PRIVATE {_target_name(library)})",
        "Drop the PRIVATE if your project links libraries without it.",
    ]
