"""
CMake projects, which covers VS Code and the CMake output of recent CubeMX.

The library gets its own CMakeLists.txt holding its file list, and the project's
CMakeLists.txt gets two lines that never change no matter how many files the
library grows to.

That library target is an INTERFACE library, not a STATIC one, and the
difference is not cosmetic. A driver's .c file includes main.h, which reaches
the HAL headers, which need the device macro and the driver include paths. CubeMX
sets those on the executable target, so a STATIC library would not see them and
would fail to compile. An INTERFACE library hands its sources to whoever links
it, so they are compiled as part of the application and inherit everything it has.
"""

import re
from pathlib import Path

from .base import ALREADY, CHANGED, MANUAL, MARK_CLOSE, MARK_OPEN, Outcome, backup, relative

NAME = "CMake"

LIBRARY_FILE = "CMakeLists.txt"

# add_executable(my_app ...) or add_library(my_lib ...)
TARGET = re.compile(r"^\s*add_(?:executable|library)\s*\(\s*([^\s)]+)", re.MULTILINE)

# CubeMX generated CMake projects define the target through the project() name.
PROJECT = re.compile(r"^\s*project\s*\(\s*([^\s)]+)", re.MULTILINE)


def detect(project_root):
    """The project's CMakeLists.txt, when this looks like a CMake project."""
    candidate = Path(project_root) / "CMakeLists.txt"

    return candidate if candidate.is_file() else None


def _find_target(text):
    """
    The CMake target to attach the library to.

    Prefers an explicit add_executable, since that is the firmware itself. Falls
    back to ${CMAKE_PROJECT_NAME}, which is what the CubeMX template uses.
    """
    match = TARGET.search(text)

    if match:
        return match.group(1)

    if PROJECT.search(text):
        return "${CMAKE_PROJECT_NAME}"

    return None


def _library_cmakelists(library):
    """The CMakeLists.txt written into the library's own folder."""
    listed = "\n".join(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/{name}" for name in library.build_sources)
    includes = " ".join(
        "${CMAKE_CURRENT_SOURCE_DIR}" if d == "." else f"${{CMAKE_CURRENT_SOURCE_DIR}}/{d}"
        for d in library.include_dirs
    )

    return f"""# Generated by stm32-installer for {library.name} {library.version}.
#
# INTERFACE, not STATIC, on purpose. These sources are compiled as part of your
# own target, so they inherit its defines and include paths. That is what lets
# {library.name}.c find main.h and the HAL headers. A STATIC library would not see
# them and would fail to compile.
#
# Edit the list below if you add files. Nothing else needs to change.

add_library({library.name} INTERFACE)

target_sources({library.name} INTERFACE
{listed}
)

target_include_directories({library.name} INTERFACE {includes})
"""


def _block(library_name, folder):
    """The two lines this tool owns inside the user's CMakeLists.txt."""
    return (
        f"{MARK_OPEN.format(name=library_name)}\n"
        f"# Added by stm32-installer. Delete this block to drop the library from\n"
        f"# the build. Its file list lives in {folder}/{LIBRARY_FILE}.\n"
        f"add_subdirectory({folder})\n"
        f"target_link_libraries(@TARGET@ PRIVATE {library_name})\n"
        f"{MARK_CLOSE.format(name=library_name)}"
    )


def integrate(cmakelists, library, destination, project_root):
    """Give the library its own CMakeLists.txt, then point the project at it."""
    path = Path(cmakelists)
    folder = relative(destination, project_root)

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not read {path.name}: {error}",
                       _manual_steps(folder, library))

    target = _find_target(text)

    if target is None:
        return Outcome(
            NAME,
            MANUAL,
            f"Could not find an add_executable or project call in {path.name}.",
            _manual_steps(folder, library),
        )

    # Written every time, so adding a source file to a library reaches everyone
    # who updates, without them editing anything.
    try:
        (Path(destination) / LIBRARY_FILE).write_text(
            _library_cmakelists(library), encoding="utf-8"
        )
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not write {folder}/{LIBRARY_FILE}: {error}",
                       _manual_steps(folder, library))

    block = _block(library.name, folder).replace("@TARGET@", target)

    open_mark = MARK_OPEN.format(name=library.name)
    close_mark = MARK_CLOSE.format(name=library.name)

    if open_mark in text:
        start = text.index(open_mark)

        if close_mark not in text:
            return Outcome(
                NAME,
                MANUAL,
                f"{path.name} has a half written stm32-installer block. Fix it by hand first.",
                _manual_steps(folder, library),
            )

        end = text.index(close_mark) + len(close_mark)

        if text[start:end] == block:
            return Outcome(NAME, ALREADY, f"{path.name} already has {library.name}.")

        saved = backup(path)
        updated = text[:start] + block + text[end:]
    else:
        saved = backup(path)
        updated = text.rstrip("\n") + "\n\n" + block + "\n"

    try:
        path.write_text(updated, encoding="utf-8")
    except OSError as error:
        return Outcome(NAME, MANUAL, f"Could not write {path.name}: {error}",
                       _manual_steps(folder, library), saved)

    return Outcome(
        NAME,
        CHANGED,
        f"Added {library.name} to {path.name}, linked to {target}.",
        backup=saved,
    )


def _manual_steps(folder, library):
    """What to paste in, when this could not do it safely."""
    return [
        "Add this to your CMakeLists.txt, using your own target name:",
        f"add_subdirectory({folder})",
        f"target_link_libraries(your_target PRIVATE {library.name})",
    ]
